name: Car Share Event Logger Unit Tests

on:
  pull_request:
    branches: [dev-master, master]
    paths-ignore:
      - "README.md"
      - ".github/**"

jobs:
  laravel-unit-tests:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        php-version: ['8.2', '8.3']

    name: PHP ${{ matrix.php-version }} Tests

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, dom, curl, libxml, zip, json, Phar, pcre, Reflection, SPL, tokenizer
          coverage: none

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Run Unit Tests
        run: vendor/bin/phpunit
